version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "4444:4444"
    environment:
      OVERRIDE_VIDEO_OUTPUT_DIR: /opt/selenoid/video
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/selenoid/video:/opt/selenoid/video"
      - "/opt/selenoid/logs:/opt/selenoid/logs"
      - "/opt/selenoid/browsers.json:/etc/selenoid/browsers.json:ro"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]